%% Search for a specified operating point for the model - Parawing.
%
% This MATLAB script is the command line equivalent of the trim model
% tab in linear analysis tool with current specifications and options.
% It produces the exact same operating points as hitting the Trim button.

% MATLAB(R) file generated by MATLAB(R) 9.1 and Simulink Control Design (TM) 4.4.
%
% Generated on: 04-May-2017 18:10:03

%% Specify the model name
model = 'Parawing_trim';

%% Create the operating point specification object.
opspec = operspec(model);

%% Set the constraints on the states in the model.
% - The defaults for all states are Known = false, SteadyState = true,
%   Min = -Inf, and Max = Inf.

% State (1) - Parawing/Parachute/Vechicle Airframe Model/Int_Xcm
% - Default model initial conditions are used to initialize optimization.
opspec.States(1).SteadyState = [false;true;false];

% State (2) - Parawing/Parachute/Vechicle Airframe Model/Int_ang_rates
% - Default model initial conditions are used to initialize optimization.

% State (3) - Parawing/Parachute/Vechicle Airframe Model/Int_euler
opspec.States(3).x = [0;-0.102;0];

% State (4) - Parawing/Parachute/Vechicle Airframe Model/Int_vel_body
opspec.States(4).x = [13.6723;0;1.2288];

%% Set the constraints on the inputs in the model.
% - The defaults for all inputs are Known = false, Min = -Inf, and
% Max = Inf.

% Input (1) - Parawing/d_l
% - Default model initial conditions are used to initialize optimization.

% Input (2) - Parawing/d_r
% - Default model initial conditions are used to initialize optimization.

%% Set the constraints on the outputs in the model.
% - The defaults for all outputs are Known = false, Min = -Inf, and
% Max = Inf.

% Output (1) - Parawing/Va
% - Default model initial conditions are used to initialize optimization.

% Output (2) - Parawing/alpha
% - Default model initial conditions are used to initialize optimization.

% Output (3) - Parawing/beta
% - Default model initial conditions are used to initialize optimization.


%% Create the options
opt = findopOptions('DisplayReport','iter');

%% Perform the operating point search.
[op,opreport] = findop(model,opspec,opt);
